apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "my-cluster-kafka-brokers.kafka.svc:9092"
  - name: consumerGroup
    value: "taskpilot-group"
  - name: authType
    value: "none"
